language: python
python:
  - "2.7"

install:
  - pip install -r requirements.txt --use-mirrors

before_script:
    - ci/before_script.sh
    - psql -c 'create database openerp_test;' -U postgres

script: cd ../openerp-server; ./openerp-server --db_user=postgres --stop-after-init --no-xmlrpc --no-xmlrpcs --no-netrpc -d openerp_test -i base
