language: python
python:
  - "2.7"

install:
  - pip install -r requirements.txt --use-mirrors

before_script:
    - git clone --depth=1 --quiet https://github.com/rvalyi/openerp-server.git ../openerp-server
    - pip install -r ../openerp-server/requirements.txt
    - git clone --depth=1 --quiet https://github.com/akretion/openerp-web.git ../openerp-web
    - psql -c 'create database openerp_test;' -U postgres


script:
    - cd ../openerp-server
    - REPOSITORIES=../openerp-addons
    - MODULES=`python -c "import os; print ','.join(list(set(os.listdir('${REPOSITORIES}')) - set(['document_ftp'])))"`
    - ./openerp-server --db_user=postgres --stop-after-init --no-xmlrpc --no-xmlrpcs --no-netrpc -d openerp_test -i $MODULES --addons-path=$REPOSITORIES,../openerp-web/addons
